name: chatapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  shared_preferences: ^2.5.2
  camera: ^0.11.1
  path_provider: ^2.1.5
  path: ^1.9.1
  video_player: ^2.9.3
  socket_io_client: ^3.0.2
  emoji_picker_flutter: ^4.3.0
  google_fonts: ^6.2.1
  flutter_secure_storage: ^9.2.4
  http: ^1.3.0
  uuid: ^4.5.1
  dart_jsonwebtoken: ^2.8.0
  web_socket_channel: ^3.0.2
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
